"use client";

import type { StickerPack } from '@/types';
import { EXPRESSIONS, PLATFORMS, PRODUCTS } from '@/lib/constants';

export function exportPackToTxt(pack: StickerPack): void {
  const platformLabel = PLATFORMS[pack.platform].label;
  const productLabel = PRODUCTS[pack.targetProduct]?.label ?? 'Sticker';
  const lines: string[] = [
    '╔══════════════════════════════════════════════╗',
    `║  StickerForge Redbubble — ${pack.concept.name}`,
    '╚══════════════════════════════════════════════╝',
    '',
    `Produk     : ${productLabel}`,
    `Platform   : ${platformLabel}`,
    pack.concept.characterType ? `Character  : ${pack.concept.characterType}` : '',
    `Style      : ${pack.concept.style}`,
    `Colors     : ${pack.concept.colors.join(', ')}`,
    `Tagline    : ${pack.concept.tagline}`,
    `Generated  : ${new Date(pack.createdAt).toLocaleString('id-ID')}`,
    '',
    '────────────────────────────────────────────────',
    'KONSEP:',
    pack.concept.description,
    pack.concept.productFit ? `\nPRODUCT FIT:\n${pack.concept.productFit}` : '',
    pack.concept.tags?.length ? `\nTAGS:\n${pack.concept.tags.join(', ')}` : '',
    '────────────────────────────────────────────────',
    '',
    '9 PROMPT DESAIN:',
    '',
    ...pack.stickers.flatMap((s) => {
      const meta = EXPRESSIONS[s.expression];
      const title = s.title ?? meta.label;
      return [
        `${s.emoji} ${title.toUpperCase()} (${meta.label})`,
        s.prompt,
        s.tips ? `Tips: ${s.tips}` : '',
        '',
      ];
    }),
    '────────────────────────────────────────────────',
    'Checklist singkat sebelum upload:',
    '- Pakai PNG jika background transparan.',
    '- Cek ukuran pixel sesuai produk Redbubble.',
    '- Preview warna cetak/CMYK karena hasil print bisa lebih muted.',
    '- Hindari brand, logo, karakter terkenal, dan likeness publik figur.',
    '────────────────────────────────────────────────',
    'Generated by StickerForge ✨  |  Redbubble prompt helper',
  ];

  const blob = new Blob([lines.filter(Boolean).join('\n')], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `stickerforge-${productLabel.toLowerCase().replace(/\s+/g, '-')}-${pack.concept.name.toLowerCase().replace(/\s+/g, '-')}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
