"use client";

import { useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, ClipboardList } from 'lucide-react';
import toast from 'react-hot-toast';
import { StickerCard } from './StickerCard';
import { StickerCardSkeleton } from './StickerCardSkeleton';
import { useCopy } from '@/hooks/useCopy';
import { EXPRESSION_ORDER, EXPRESSIONS, PLATFORMS, PRODUCTS } from '@/lib/constants';
import type { StickerPrompt, Expression, CharacterConcept, Platform, ProductType } from '@/types';

interface StickerGridProps {
  stickers: StickerPrompt[];
  concept: CharacterConcept | null;
  platform: Platform;
  targetProduct: ProductType;
  isGenerating: boolean;
  onRegenerate: (expression: Expression) => void;
  onExport: () => void;
}

export function StickerGrid({
  stickers,
  concept,
  platform,
  targetProduct,
  isGenerating,
  onRegenerate,
  onExport,
}: StickerGridProps) {
  const { copied, copy } = useCopy();

  const receivedExpressions = new Set(stickers.map((s) => s.expression));
  const pendingExpressions = EXPRESSION_ORDER.filter(
    (e) => !receivedExpressions.has(e)
  );

  const handleCopyAll = useCallback(() => {
    if (!concept || stickers.length === 0) return;
    const platformLabel = PLATFORMS[platform].label;
    const productLabel = PRODUCTS[targetProduct].label;
    const lines = [
      `═══ StickerForge Redbubble Pack — ${concept.name} ═══`,
      `Produk: ${productLabel}`,
      `Platform AI: ${platformLabel}`,
      concept.characterType ? `Character type: ${concept.characterType}` : '',
      `Style: ${concept.style}`,
      `Colors: ${concept.colors.join(', ')}`,
      concept.productFit ? `Product fit: ${concept.productFit}` : '',
      concept.tags?.length ? `Tags: ${concept.tags.join(', ')}` : '',
      '',
      ...stickers.map((s) => {
        const meta = EXPRESSIONS[s.expression];
        const title = s.title ?? meta.label;
        return `--- ${s.emoji} ${title.toUpperCase()} (${meta.label}) ---\n${s.prompt}`;
      }),
      '',
      `Generated by StickerForge ✨`,
    ].filter(Boolean);
    copy(lines.join('\n'));
    toast.success('Semua prompt tersalin! 📋');
  }, [concept, stickers, platform, targetProduct, copy]);

  if (!isGenerating && stickers.length === 0) return null;

  return (
    <motion.section
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="space-y-4"
      aria-label="Prompt desain yang di-generate"
    >
      <div className="flex items-center justify-between flex-wrap gap-2">
        <h2 className="font-display font-bold text-lg text-kawaii-text">
          {PRODUCTS[targetProduct].emoji} 9 Prompt Desain {PRODUCTS[targetProduct].shortName}
          {stickers.length > 0 && (
            <span className="ml-2 text-sm font-body text-kawaii-muted font-normal">
              ({stickers.length}/9 selesai)
            </span>
          )}
        </h2>

        {stickers.length === 9 && (
          <div className="flex gap-2">
            <button
              onClick={handleCopyAll}
              className="flex items-center gap-1.5 px-4 py-2 rounded-kawaii-sm bg-primary-100 text-primary-700 border border-primary-200 font-body font-semibold text-sm hover:bg-primary-200 transition-all active:scale-95 focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2"
              aria-label="Salin semua prompt sekaligus"
            >
              <ClipboardList className="w-4 h-4" aria-hidden="true" />
              {copied ? 'Tersalin!' : 'Salin Semua'}
            </button>
            <button
              onClick={onExport}
              className="flex items-center gap-1.5 px-4 py-2 rounded-kawaii-sm bg-accent-200 text-green-700 border border-accent-300 font-body font-semibold text-sm hover:bg-accent-300 transition-all active:scale-95 focus-visible:ring-2 focus-visible:ring-green-500 focus-visible:ring-offset-2"
              aria-label="Ekspor semua prompt ke file .txt"
            >
              <Download className="w-4 h-4" aria-hidden="true" />
              Export .txt
            </button>
          </div>
        )}
      </div>

      <div
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3"
        role="list"
        aria-live="polite"
        aria-label="Daftar prompt desain"
      >
        <AnimatePresence mode="popLayout">
          {stickers.map((sticker, idx) => (
            <div key={sticker.expression} role="listitem">
              <StickerCard
                sticker={sticker}
                onRegenerate={onRegenerate}
                isRegenerating={isGenerating}
                index={idx}
                targetProduct={targetProduct}
              />
            </div>
          ))}

          {isGenerating &&
            pendingExpressions.map((expr) => (
              <div key={`skeleton-${expr}`} role="listitem" aria-hidden="true">
                <StickerCardSkeleton />
              </div>
            ))}
        </AnimatePresence>
      </div>
    </motion.section>
  );
}
